import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
Selenium_Ruby = driver.find_element_by_xpath("//*[@class='attachment-shop_catalog size-shop_catalog wp-post-image']")
Selenium_Ruby.click()
Reviews = driver.find_element_by_css_selector("[href='#tab-reviews']")
Reviews.click()
Rating = driver.find_element_by_xpath("//*[@class='star-5']")
Rating.click()
Comment = driver.find_element_by_id("comment")
Comment.send_keys("Nice book!")
Name = driver.find_element_by_id("author")
Name.send_keys("Sergey")
Email = driver.find_element_by_id("email")
Email.send_keys("mail@mail.ru")
Submit = driver.find_element_by_id("submit")
Submit.click()
driver.quit()