import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
driver = webdriver.Chrome()
driver.get("http://practice.automationtesting.in/")
Shop = driver.find_element_by_link_text("Shop")
Shop.click()
driver.execute_script("window.scrollBy(0, 300);")
HTML5Web = driver.find_element_by_css_selector("[href='/shop/?add-to-cart=182']")
HTML5Web.click()
time.sleep(5)
Basket = driver.find_element_by_xpath("//*[@class='cartcontents']")
Basket.click()
Checkout = driver.find_element_by_css_selector("[href='http://practice.automationtesting.in/checkout/']")
Checkout.click()
FirstName = driver.find_element_by_id("billing_first_name")
FirstName.send_keys("Sergey")
LastName = driver.find_element_by_id("billing_last_name")
LastName.send_keys("Gruzdev")
Email = driver.find_element_by_id("billing_email")
Email.send_keys("mail@mail.ru")
Phone = driver.find_element_by_id("billing_phone")
Phone.send_keys("(812)565-67-33")
Country = driver.find_element_by_id("select2-chosen-1")
Country.click()
Country2 = driver.find_element_by_id("s2id_autogen1_search")
Country2.send_keys("Finland")
Country3 = driver.find_element_by_id("select2-result-label-274")
Country3.click()
Adress = driver.find_element_by_id("billing_address_1")
Adress.send_keys("Helsinki")
Post = driver.find_element_by_id("billing_postcode")
Post.send_keys("23456")
City = driver.find_element_by_id("billing_city")
City.send_keys("Helsinki")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(10)
Check = driver.find_element_by_id("payment_method_cheque")
Check.click()
Place = driver.find_element_by_id("place_order")
Place.click()
element = WebDriverWait(driver, 20).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
element2 = WebDriverWait(driver, 20).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".method"), "Check Payments"))